name = "FuzzyCRegression"
uuid = "f92c8a04-155b-4747-b198-4c6b1c04e8f7"
authors = ["Aidan Toner-Rodgers"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
